### ISSUE TITLE
Please fix the demo

### ISSUE THREAD

**Issue by DanielWLam** [charliekassel/vuejs-datepicker#309] opened 2017-09-28 08:17 UTC
Hi, the demo seems broken... Hope it can be fixed as soon as possible. https://www.webpackbin.com/bins/-KhQbtTSVuU6r8VCrIdC

**Comment by charliekassel** [comment] 2017-09-28 08:36
Duplicate of #308

**Closed by charliekassel** 2017-09-28 08:36 UTC
