### ISSUE TITLE
Date is off by one day 

### ISSUE THREAD

**Issue by IstvanLovas** [charliekassel/vuejs-datepicker#23] opened 2016-10-23 14:27 UTC
Hi!

When i select the date, the output is off by 1 day. I assume it is a timezone issue however i am unable to find any solution. Here is the code:

// In template
<datepicker placeholder="Select date of shoot"
                     :value.sync="formInputs.date"
                     :format="format"
                     name="date"

> </datepicker>

// The data

data() {
     return {
         formInputs: {
              date: new Date()
        },
        format: 'd MMMM yyyy',
    }
}

And the screenshot:

![screen shot 2016-10-23 at 15 24 37](https://cloud.githubusercontent.com/assets/7696734/19626962/de3ab86e-9934-11e6-8e36-9205c30fa489.png)

I appreciate any help i can get :)
Thank You!

**Comment by skbogner** [comment] 2016-11-17 14:28
I belive that is midnight your time (but displayed in UTC).

**Comment by LasseRafn** [comment] 2017-01-12 11:02
I have this too, one day off.

"2016-12-06T23:00:00.000Z" should be 2016-12-07

**Comment by skbogner** [comment] 2017-01-12 12:42
As per my previous comment. If you're in UTC+1 I believe the timestamp:

'2016-12-06T23:00:00.000Z'

corresponds to midnight YOUR TIME: 2016-12-07 24:00:00

**Comment by mailnike** [comment] 2017-01-14 14:16
how to address this issue? I am facing same problem. Is there anyway to get client time?

**Comment by LasseRafn** [comment] 2017-01-16 13:17
I discovered that (After reading @skbogner's comment) that this is not really a problem.

How I decided to handle the data (I needed to post it to a url, in Y-m-d format) was this:

````js
const date = new Date(formInputs.date);
let date_for_request = date.getFullYear() + '-'
                                          + ('0' + (date.getMonth()+1)).slice(-2) + '-'
                                          + ('0' + date.getDate()).slice(-2);
````

**HOWEVER** I imagine that you do not even need to reformat it, as the outputted format is fine (as skbogner's comment states; it's simply because of timezones)

**Comment by sjmarve** [comment] 2017-01-23 07:13
Also having this issue when using `v-model` attribute. The date is off by one day. And the date is not following the `format` passed in

**Comment by charliekassel** [comment] 2017-01-23 07:16
@sjmarve - The date is output as a Date object - format is only a visual representation in the text input.

**Comment by mailnike** [comment] 2017-01-24 11:31
@all - hey guys, I am using this as it is with laravel 5.3 and it doesn't causes any issue. **So don't worry if it looks like date is off by a day.**

**Comment by SDJeff** [comment] 2017-01-25 16:55
It is a bug. The Input shows the correct value but saved at the model is Day minus 1 hour.
So if you take your example:

`
selectedDate: {
                    date: new Date(2016, 9,  16)
                }


<datepicker input-class="input" name="booking_date" :value="selectedDate.date" language="de" placeholder="Buchungsdatum"></datepicker>
`

Box will Show 16 Okt 2016 and the model is (if inspect it)

selectedDate:Object
date:"2016-10-15T22:00:00.000Z"

**Comment by mailnike** [comment] 2017-01-26 04:23
@SDJeff try 

```moment().format('YYYY-MM-DD'),```

**Comment by SDJeff** [comment] 2017-01-26 05:53
The problem is, that javascript returns a date Object as UTC. So you have first to convert it back to your local timezone like it is at the browser if you work with it in the console.

So i added a vuejs2 watch for the v-model field of the DatePicker and format it new with moment like so in my destination field:

>  watch: {
>             // whenever dateValue in booking_date changes, this function will run
>             booking_date: function (date) {
>                   let d =  new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate(), date.getHours(), date.getMinutes(), date.getSeconds()));
>                   this.currentStamp.booking_date = moment(d).format("YYYY-MM-DD")
>             }
>         },

be sure to import moment.js before:
`import moment from 'moment';`

**Comment by adrianmejias** [comment] 2017-01-26 16:51
I came across this issue and ended up setting the date to YYYY/MM/DD instead of YYYY-MM-DD, which corrected the issue

more info here http://stackoverflow.com/a/31732581/221830

**Comment by avonian** [comment] 2017-01-28 18:59
i'm having the same problem but none of the explanations above make much sense to me... when i pick something on datepicker it shows fine... saves to db fine... when i reload that object, date comes into vue component just fine... but on datepicker input control it shows one day behind... why would datepicker manipulate that for display purposes? that makes no sense I mean how does it even know what the TZ of the date being loaded is?

**Comment by avonian** [comment] 2017-01-28 19:21
is there any way to get this thing to just respect the date value and not manipulate/convert anything?

**Comment by raphcadiz** [comment] 2017-02-14 09:54
I have this the same issue. I formatted it to yyyy-MM-dd. I tried 2012-12-13
I get this instead "2012-12-12T16:00:00.000Z" . I need it to be just '2012-12-13' any fix for this?

**Comment by javisperez** [comment] 2017-02-17 15:12
@raphcadiz how are you formatting the date?

**Comment by raphcadiz** [comment] 2017-02-17 16:26
@javisperez, I did it like this :format="'yyyy-MM-dd'" I did get the correct format to show but when I bind it to the data I get the other long format I mention above

**Comment by julesjanssen** [comment] 2017-02-23 14:01
Another option is adjust the resulting date object with the outcome of `(new Date).getTimezoneOffset()` (by using `setMinutes`)

**Comment by charliekassel** [comment] 2017-02-24 20:45
@raphcadiz you are recieving the javascript Date object, not a formatted string.
With the Date object you can format as you wish.

I am closing this issue as I think this is due to timezones.

**Closed by charliekassel** 2017-02-24 20:45 UTC

**Comment by hkmsadek** [comment] 2021-07-12 09:09
this is shit bug and these guys never updated it.. such a shame

**Comment by ogmo0n** [comment] 2023-08-01 14:18
I switched to vue-datetime and the fix for that was using the value-zone prop and passing in timezone.
`:value-zone="Intl.DateTimeFormat().resolvedOptions().timeZone"` 
https://www.npmjs.com/package/vue-datetime
Not sure if this is what you want, but it worked for me.
