### ISSUE TITLE
Invalid prop: custom validator check failed for prop "value".

### ISSUE THREAD

**Issue by MadReal** [charliekassel/vuejs-datepicker#383] opened 2018-01-03 15:53 UTC
Hello, I have a problem with `v-model` and `:value` both, no matter what I do I get this error:
```
[Vue warn]: Invalid prop: custom validator check failed for prop "value".

found in

---> <Datepicker>
```

Template
`<datepicker :value="selectedCoin.bought_on_ts" name="date-picker-bought_on_ts" format="MM/dd/yyyy" input-class="vdp-datepicker__input")></datepicker>`

the property is this (if I check it from vue inspector): `bought_on_ts:"2018-01-03T15:49:33.624Z"`

I do this on "created" `this.selectedCoin.bought_on_ts = new Date()` to define today's date.

**Comment by charliekassel** [comment] 2018-04-26 19:43
This looks like it should be fine so not sure what the issue is.
Closing now, but feel free to reopen if you're still having issues.

**Closed by charliekassel** 2018-04-26 19:43 UTC

**Comment by khataev** [comment] 2019-05-15 18:00
I have the same issue, and it is very strange! When I bind value to variable like:
```
const date = new Date(2016, 8, 16)
```

everything is ok. But when I get date from moment.js object or luxon DateTime (which is native js Date itself):

```
const date2 = moment('2016-09-16').toDate()
const date3 = DateTime.local(2016, 9, 16).toJSDate()
```

I get error: 

```
[Vue warn]: Invalid prop: custom validator check failed for prop "value".

found in

---> <DatePicker>
       <StaticPositionsTab> at components/StaticPositions.vue
         <BTab>
           <BTabs>
             <Pages/index.vue> at pages/index.vue
               <Nuxt>
                 <Layouts/default.vue> at layouts/default.vue
                   <Root>
```

I found custom validator for value property:

```
validateDateInput (val) {
    return val === null || val instanceof Date || typeof val === 'string' || typeof val === 'number'
  }
```

and it looks pretty straightforward and clear it returns true in every case, so I don't understand, why validation error happens. Could it be Vue's bug?

**Comment by sebenik** [comment] 2019-08-23 07:18
I get the same error

**Comment by michug** [comment] 2019-12-11 20:29
same here from a quasar framework QDatetime q-input

**Comment by nguyenquilong** [comment] 2019-12-16 06:54
Hi, you can set your data is null, like this
` <vue-pikaday
                  v-model="form.ToDateReview"
                  :options="pikadayOptions"
                  placeholder="ToDateReview"
                />`
` data() {
    return {
form: {
ToDateReview: null
}
  }`

**Comment by ShejaEddy** [comment] 2020-03-31 21:55
Hi, setting it to null seems to work but what if you have a date in your `v-model` and you want it displayed in the input field as its value?

**Comment by ShejaEddy** [comment] 2020-03-31 22:29
Hi, setting it to null seems to work but what if you have a date in your `v-model` and you want it displayed in the input field as its value?
