### ISSUE TITLE
Required attribute gets submitted without value

### ISSUE THREAD

**Issue by syed-haroon** [charliekassel/vuejs-datepicker#353] opened 2017-11-15 06:05 UTC
Setting html required attribute on input fields doesn't work as expected and submits the form without have a input value.

Tried to get help from stackoverflow community, so far did not hear anything:
https://stackoverflow.com/q/47280866/1292050

**Comment by sv1979** [comment] 2018-03-01 03:15
Have got the same issue, seems like has not been fixed. Form submits without value selected

**Comment by adamwright104** [comment] 2018-03-26 14:20
When will this be fixed?

**Comment by isatrio** [comment] 2018-04-01 12:28
For temporary solution you can refer my forking branch here https://github.com/isatrio/vuejs-datepicker. if you use Yarn use command below

yarn add git+https://github.com/isatrio/vuejs-datepicker.git#production

**Comment by adamwright104** [comment] 2018-04-03 08:37
Hi i also fixed this by removing the read-only from the input after it renders. simply loop through and remove. would be cool if the plugin does this but not an issue for my project.

**Comment by charliekassel** [comment] 2018-04-26 19:46
This should be resolved in v1 as the readonly attribute is removed.

**Closed by charliekassel** 2018-04-26 19:46 UTC

**Comment by mik13ST** [comment] 2021-09-01 08:57
I am using version 1.6.2 and the problem is back. The readonly attribute is still there.

The issue is not resolved.

**Comment by mik13ST** [comment] 2021-09-07 14:22
I dug into it further and came up with a [reasonable solution](https://stackoverflow.com/a/69026389/5951116). I added it as an [answer ](https://stackoverflow.com/a/69033194/5951116) to the [mentioned StackOverflow question](https://stackoverflow.com/q/47280866/5951116).

I resolve this by allowing user input (which removes `readonly`) and then suppressing all user input manually.

But still, it's an issue of this library.
