### ISSUE TITLE
Datepicker does not validate with vee-validate with disabled dates.

### ISSUE THREAD

**Issue by magnhalv** [charliekassel/vuejs-datepicker#438] opened 2018-03-13 11:54 UTC
Disclaimer, I'm a bit uncertain if this is the right place to post this, since the issues arises when synchonizing this component with vee-validate. 

If I disable some dates in the datepicker, I am unable to validate required date fields. 

See example below. Two datepickers, both a set up to being validated as required by vee-validate, but the one with the "disabled" attribute is not validated. 
https://codesandbox.io/s/387mjz0j4q

**Comment by alex3683** [comment] 2018-03-26 07:09
The cause is the way vee-validate detects whether a field is disabled or not. There's simply a check for the truthyness of the `disabled` attribute (see https://github.com/baianat/vee-validate/blob/605f71ed05cf7d1760bd8da1323398acd2ca2d88/src/core/field.js#L115).

This isn't easy to resolve, since for vee-validate `disabled` is either `true` or `false`: You can input a value or not. For the datepicker `disabled` is interpreted during selection and possibly only limits the selectable range but not completely disables selection.

Just my personal opinion, but using `disabled` for this behavior perhaps wasn't a good choice. Perhaps one could add an alternative attribute (`disable-selection` or so) for this that doesn't interfere with default HTML input semantics.

**Comment by charliekassel** [comment] 2018-03-26 17:07
This issue is also mentioned here: https://github.com/charliekassel/vuejs-datepicker/issues/379

I've been apprehensive to change this property based on the need of another library, but I realise this is a popular library and there's no specific reason I for us to use `disabled` as the property name so I will change this to a more verbose name for the upcoming v1 release.

**Comment by RomeroMsk** [comment] 2018-04-03 06:01
@charliekassel, how long it can take to release v1?

**Comment by charliekassel** [comment] 2018-04-04 18:37
There's quite a lot of changes I want to make and I've not found as much time as I'd hoped to work on this over the last couple of weeks, but I'm hoping by end of April I'll have a release out.

**Comment by charliekassel** [comment] 2018-04-26 19:40
This should be resolved in v1

**Closed by charliekassel** 2018-04-26 19:40 UTC
